{{- if .Values.monitoring.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
spec:
  selector:
    matchLabels: {app: vllm}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
